project:
  type: website
  render:
    - "index.qmd"
    - "about.qmd"
    - "Hands-on_Ex/*.qmd"
    - "In Class Exercise/*.qmd"
    - "Take Home Exercise 1/*.qmd"

website:
  title: "Exploring Visual Analytics"
  navbar:
    logo: images/VisualAnalyticsJourney.png
    title: false
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "1. A Layered Grammar of Graphics"
            href: "Hands-on_Ex/Hands-on_Ex01.qmd"
          - text: "2. Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02.qmd"
          - text: "3a. Programming Interactive Data Visualisation"
            href: "Hands-on_Ex/Hands-on_Ex03a.qmd"
          - text: "3b. Programming Animated Statistical Graphics"
            href: "Hands-on_Ex/Hands-on_Ex03b.qmd"
          - text: "4a. Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04a.qmd"
          - text: "4b. Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04b.qmd"
          - text: "4c. Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_Ex04c.qmd"
          - text: "4d. Building Funnel Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex04d.qmd"
          - text: "5a. Building Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex05a.qmd"
          - text: "5b. Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex05b.qmd"
          - text: "5c. Visual Multivariate Analysis with Heatmap"
            href: "Hands-on_Ex/Hands-on_Ex05c.qmd"
          - text: "5d. Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05d.qmd"
          - text: "5e. Treemap Visualisation"
            href: "Hands-on_Ex/Hands-on_Ex05e.qmd"
          - text: "7a. Modelling, Visualising and Analysing Network Data"
            href: "Hands-on_Ex/Hands-on_Ex07a.qmd"
          - text: "7b. Visualising and Analysing Text Data"
            href: "Hands-on_Ex/Hands-on_Ex07b.qmd"
  
      - text: "In-Class Exercises"
        menu:
          - text: "In-Class Exercise 2"
            href: "In Class Exercise/In-class_Ex02.qmd"
          - text: "In-Class Exercise 3"
            href: "In Class Exercise/In-class_Ex03.qmd"
          - text: "In-Class Exercise 4"
            href: "In Class Exercise/In-class_Ex04.qmd"
          - text: "In-Class Exercise 5"
            href: "In Class Exercise/In-class_Ex05.qmd"
          - text: "In-Class Exercise 6"
            href: "In Class Exercise/In-class_Ex06.qmd"
      - text: "Take-Home Exercises"
        menu:
          - text: "Take-Home Exercise 1"
          - text: "Technical Report"
            href: "Take Home Exercise 1/Take_Home_Ex01.qmd"
          - text: "Executive Summary"
            href: "Take Home Exercise 1/Take_Home_Ex01_slides.qmd"
            
    right:
      - icon: heart-fill
        href: about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual