{
  "hash": "091d0567f3cc0d226c92d070a2cd7d71",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Uncovering Loss Drivers in Motor Vehicle Insurance Portfolio using Data Visualisation\"\nauthor: \"Carina Peh\"\ndate: \"May 17, 2026\"\ndate-modified: \"last-modified\"\ndescription: \"Applying univariate and bivariate visual analytics techniques to explore key factors influencing profitability and volatility in a motor vehicle insurance portfolio.\"\nimage: images/takehome1.png\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n  code-fold: true\n---\n\n# 1 Overview\n\n## 1.1 Background\n\nThe Property & Casualty (P&C) insurance industry has long struggled with underperforming portfolios where the root causes of poor profitability and high volatility remain unknown. Traditional approaches to data-driven decision-making in insurance have largely focused on dashboard reporting, which is limited by the general lack of advanced analytical capabilities which offers a more powerful alternative. By combining data science, risk knowledge and industry expertise, insurers can generate actionable insights to grow, optimise existing portfolios and improve operational efficiency. As noted by the Swiss Re Institute (2019), leveraging visual analytics can potentially help investigate trends in underlying loss drivers, while data enrichment using external data can help refine segmentation and underwriting strategy.\n\nIn this study, a motor vehicle insurance portfolio dataset from a Spanish insurance company, made publicly available via Mendeley Data, is used to demonstrate the potential of visual analytics techniques in exploring and analysing key factors influencing portfolio profitability and volatility.\n\n## 1.2 The Data\n\nThe data for this exercise is the motor vehicle insurance portfolio dataset retrieved from [Mendeley Data](https://data.mendeley.com/datasets/sw4jmdb2sm/1).\n\nThe dataset contains **354,140 policy records** across **47 variables**, covering the period from 2022 to 2024. Variables are grouped into four broad categories:\n\n| Category | Description |\n|------------------------------------|------------------------------------|\n| Policy & Insured characteristics | Policy type, status, business origin, payment frequency, bonus score |\n| Driver & Vehicle characteristics | Driver age, vehicle age, fuel type, vehicle brand, vehicle value, area |\n| Premiums | Total and coverage-level premiums collected |\n| Exposure, Claims & Incurred | Claims counts, incurred costs, and exposure duration |\n\n## 1.3 The Task\n\nUsing appropriate **Exploratory Data Analysis (EDA)** methods and **ggplot2** functions, this study aims to:\n\n-   Apply suitable **univariate** visual analytics techniques to explore the distributions and characteristics of numerical and categorical variables.\n\n-   Apply suitable **bivariate** visual analytics techniques to investigate and statistically validate factors influencing the **profitability** and **volatility** of the insurance portfolio.\n\n# 2 Loading Packages\n\n| Package | Description |\n|------------------------------------|------------------------------------|\n| [**tidyverse**](https://www.tidyverse.org/) | A collection of R packages designed for data science, used for data import, wrangling and transformation |\n| [**readxl**](https://readxl.tidyverse.org/) | For reading Excel files such as the variable cookbook |\n| [**knitr**](https://yihui.org/knitr/) | For dynamic report generation and displaying formatted tables |\n| [**patchwork**](https://patchwork.data-imaginist.com/) | For combining multiple ggplot2 plots into a single composite figure |\n| [**ggthemes**](https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/) | Extra themes, geoms and scales for ggplot2 |\n| [**scales**](https://scales.r-lib.org/) | For formatting axis labels and annotations in ggplot2 |\n| [**ggridges**](https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html) | For creating ridgeline plots to visualise distributions |\n| [**ggdist**](https://mjskay.github.io/ggdist/) | For visualising distributions and uncertainty |\n| [**ggpubr**](https://rpkgs.datanovia.com/ggpubr/) | For creating publication-ready ggplot2 plots |\n| [**ggstatsplot**](https://indrajeetpatil.github.io/ggstatsplot/) | For combining statistical tests with visualisations |\n| [**ggiraph**](https://davidgohel.github.io/ggiraph/) | For adding interactivity to ggplot2 visualisations |\n| [**naniar**](https://naniar.njtierney.com/) | For visualising and summarising missing values |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, readxl, knitr,\n               patchwork, ggthemes, scales,\n               ggridges, ggdist, ggpubr,\n               ggstatsplot, naniar, ggiraph)\n```\n:::\n\n\n# 3 Importing the Data\n\nIn this section, the following steps are taken to import and perform initial checks on the data, from reading in the raw data to verifying its structure. The **tidyverse** package will be used, specifically **readr** for reading in the data and **dplyr** for data manipulation.\n\nThe code chunk below imports the motor vehicle insurance portfolio dataset using `read_delim()` of the **readr** package. The dataset uses a semicolon (`;`) as its delimiter instead of a comma, so `delim = \";\"` is specified.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- read_delim(\"Dataset of motor insurance portfolio.csv\",\n                        delim = \";\",\n                        show_col_types = FALSE)\n```\n:::\n\n\nThe dataset is in a tibble dataframe, containing **354,140 observations (rows)** across **47 variables (columns)**. Each observation corresponds to a motor vehicle insurance policy record from a Spanish non-life insurance company.\n\nWe use `glimpse()` of the **dplyr** package to get a quick overview of the dataset structure, including the number of rows, columns and data types of each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\nBefore moving on, duplicated records are checked to prevent duplicates in our analysis using `group_by_all()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicate <- insurance %>%\n  group_by_all() %>%\n  filter(n() > 1) %>%\n  ungroup()\n\nduplicate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 47\n# ℹ 47 variables: insured_id <dbl>, year <dbl>, policy_type <chr>,\n#   policy_status <chr>, business_type <chr>, payment_frequency <chr>,\n#   bonus_score <chr>, driver_age <dbl>, vehicle_age <dbl>,\n#   age_driving_licence <dbl>, fuel_type <chr>, vehicle_value <dbl>,\n#   seats <dbl>, power_to_weight_ratio <dbl>, vehicle_brand <chr>,\n#   municipality_type <chr>, circulation_area <chr>, total_premium <dbl>,\n#   liability_premium <dbl>, property_damage_premium <dbl>, …\n```\n\n\n:::\n:::\n\n\nMissing values are also checked across all columns using `colSums()` and `is.na()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(insurance))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 insured_id                        year \n                          0                           0 \n                policy_type               policy_status \n                          0                           0 \n              business_type           payment_frequency \n                          0                           0 \n                bonus_score                  driver_age \n                          0                           0 \n                vehicle_age         age_driving_licence \n                          2                           2 \n                  fuel_type               vehicle_value \n                       1287                         513 \n                      seats       power_to_weight_ratio \n                          0                           0 \n              vehicle_brand           municipality_type \n                          0                           0 \n           circulation_area               total_premium \n                          0                           0 \n          liability_premium     property_damage_premium \n                          0                           0 \n              theft_premium                fire_premium \n                          0                           0 \n              glass_premium    legal_protection_premium \n                          0                           0 \n          occupants_premium                total_claims \n                          0                           0 \n           liability_claims   liability_property_claims \n                          0                           0 \n    liability_injury_claims             property_claims \n                          0                           0 \n               theft_claims                 fire_claims \n                          0                           0 \n               glass_claims     legal_protection_claims \n                          0                           0 \n           occupants_claims              total_incurred \n                          0                           0 \n         liability_incurred liability_property_incurred \n                          0                           0 \n  liability_injury_incurred           property_incurred \n                          0                           0 \n             theft_incurred               fire_incurred \n                          0                           0 \n             glass_incurred   legal_protection_incurred \n                          0                           0 \n         occupants_incurred              total_exposure \n                          0                           0 \n         liability_exposure \n                          0 \n```\n\n\n:::\n:::\n\n\nThe results show that four variables contain missing values — `fuel_type` (1,287), `vehicle_value` (513), `vehicle_age` (2) and `age_driving_licence` (2). These will be handled in the Data Wrangling section.\n\n# 4 Data Wrangling\n\nThe following flowchart shows the main variables used and created in this study.\n\n```{mermaid}\nflowchart LR\n    A(Motor Insurance\\nPortfolio) -->|Select| B[Policy &\\nInsured\\nCharacteristics]\n    A -->|Select| C[Driver & Vehicle\\nCharacteristics]\n    A -->|Select| D[Premiums]\n    A -->|Select| E[Exposure,\\nClaims &\\nIncurred]\n\n    B --> B1([policy_type])\n    B --> B2([policy_status])\n    B --> B3([business_type])\n    B --> B4([payment_frequency])\n    B --> B5([bonus_score])\n\n    C --> C1([driver_age])\n    C --> C2([vehicle_age])\n    C --> C3([vehicle_value])\n    C --> C4([fuel_type])\n    C --> C5([vehicle_brand])\n    C --> C6([municipality_type])\n    C --> C7([circulation_area])\n\n    D --> D1([total_premium])\n    D --> D2([liability_premium])\n    D --> D3([property_damage_premium])\n    D --> D4([theft_premium])\n    D --> D5([fire_premium])\n    D --> D6([glass_premium])\n    D --> D7([legal_protection_premium])\n    D --> D8([occupants_premium])\n\n    E --> E1([total_exposure])\n    E --> E2([total_claims])\n    E --> E3([total_incurred])\n    E --> E4([loss_ratio])\n    E --> E5([claim_frequency])\n    E --> E6([has_claim])\n```\n\n## 4.1 Variable Selection\n\nBelow are the variables retained for this study, which can be grouped into 4 broad categories of Policy & Insured Characteristics, Driver & Vehicle Characteristics, Premiums, and Exposure, Claims & Incurred. Details are extracted from the cookbook(`Descriptive_of_variables.xlsx`):\n\n| Category | Variable | Description | Type | Encoding |\n|---------------|---------------|---------------|---------------|---------------|\n| Policy & Insured | `policy_type` | Main coverage structure | CAT | TP, TPG, CC, COMP_E, COMP_N |\n| Policy & Insured | `policy_status` | Policy active or cancelled | CAT | A - Active, C - Cancelled |\n| Policy & Insured | `business_type` | Business origin | CAT | NB - New Business, P - Portfolio |\n| Policy & Insured | `payment_frequency` | Billing frequency | CAT | A - Annual, S - Semi-annual, Q - Quarterly |\n| Policy & Insured | `bonus_score` | Past claims experience | CAT | G - Good, N - Neutral, B - Bad |\n| Driver & Vehicle | `driver_age` | Age of main driver | NUM | In years |\n| Driver & Vehicle | `vehicle_age` | Age of insured vehicle | NUM | In years |\n| Driver & Vehicle | `vehicle_value` | Declared insured value | NUM | In euros (€) |\n| Driver & Vehicle | `fuel_type` | Vehicle fuel type | CAT | D - Diesel, G - Gasoline |\n| Driver & Vehicle | `vehicle_brand` | Brand of vehicle | CAT | 65 brands |\n| Driver & Vehicle | `municipality_type` | Geographic classification | CAT | I - Inland, C - Coastal, IS - Islands |\n| Driver & Vehicle | `circulation_area` | Circulation environment | CAT | U - Urban, R - Rural |\n| Premiums | `total_premium` | Total premium collected | NUM | In euros (€) |\n| Premiums | `liability_premium` | Liability coverage premium | NUM | In euros (€) |\n| Premiums | `property_damage_premium` | Property damage premium | NUM | In euros (€) |\n| Premiums | `theft_premium` | Theft coverage premium | NUM | In euros (€) |\n| Premiums | `fire_premium` | Fire coverage premium | NUM | In euros (€) |\n| Premiums | `glass_premium` | Glass coverage premium | NUM | In euros (€) |\n| Premiums | `legal_protection_premium` | Legal protection premium | NUM | In euros (€) |\n| Premiums | `occupants_premium` | Occupants coverage premium | NUM | In euros (€) |\n| Exposure, Claims & Incurred | `total_exposure` | Time-on-risk in policy years | NUM | 0 to 1 |\n| Exposure, Claims & Incurred | `total_claims` | Total claims reported | NUM | Count |\n| Exposure, Claims & Incurred | `total_incurred` | Total incurred cost of claims | NUM | In euros (€) |\n| Exposure, Claims & Incurred | `loss_ratio`\\* | Profitability measure | NUM | total_incurred / total_premium |\n| Exposure, Claims & Incurred | `claim_frequency`\\* | Volatility measure | NUM | total_claims / total_exposure |\n| Exposure, Claims & Incurred | `has_claim`\\* | Binary claim indicator | NUM | 1 if claims \\> 0, else 0 |\n\n\\*Derived variables created in Section 4.5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  select(insured_id, year,\n         policy_type, policy_status, business_type,\n         payment_frequency, bonus_score,\n         driver_age, vehicle_age, age_driving_licence,\n         fuel_type, vehicle_value, seats,\n         power_to_weight_ratio, vehicle_brand,\n         municipality_type, circulation_area,\n         total_premium, liability_premium,\n         property_damage_premium, theft_premium,\n         fire_premium, glass_premium,\n         legal_protection_premium, occupants_premium,\n         total_exposure, liability_exposure,\n         total_claims, total_incurred)\n```\n:::\n\n\nThe resulting dataset retains **354,140 observations** across **30 variables**.\n\n## 4.2 Handling Missing Values\n\n`is.na()` allows us to identify missing values in our dataset and `sum()` counts the frequency of such missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(insurance$fuel_type))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1287\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(insurance$vehicle_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 513\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(insurance$vehicle_age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(insurance$age_driving_licence))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n`gg_miss_var()` of the **naniar** package is used here as it provides a visual overview of missingness ranked by frequency, which is more informative than a raw count table when comparing across many variables simultaneously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_miss_var(insurance)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe results show that four variables contain missing values:\n\n| Variable              | Missing Count | \\% of Total |\n|-----------------------|---------------|-------------|\n| `fuel_type`           | 1,287         | 0.36%       |\n| `vehicle_value`       | 513           | 0.14%       |\n| `vehicle_age`         | 2             | \\<0.01%     |\n| `age_driving_licence` | 2             | \\<0.01%     |\n\nAs the missing values are very small in proportion (less than 0.5% of the total dataset), they will not significantly affect the analysis. `drop_na()` drops rows where any column specified contains a missing value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- drop_na(insurance,\n                     fuel_type, vehicle_value,\n                     vehicle_age, age_driving_licence)\ninsurance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 352,338 × 29\n   insured_id  year policy_type policy_status business_type payment_frequency\n        <dbl> <dbl> <chr>       <chr>         <chr>         <chr>            \n 1          1  2022 COMP_E      C             NB            A                \n 2          2  2022 COMP_E      A             P             A                \n 3          2  2023 COMP_E      A             P             A                \n 4          2  2024 COMP_E      A             P             A                \n 5          3  2022 COMP_E      A             NB            S                \n 6          3  2023 COMP_E      A             P             S                \n 7          3  2024 COMP_E      A             P             S                \n 8          4  2022 CC          A             NB            A                \n 9          4  2023 CC          A             P             A                \n10          4  2024 CC          A             P             A                \n# ℹ 352,328 more rows\n# ℹ 23 more variables: bonus_score <chr>, driver_age <dbl>, vehicle_age <dbl>,\n#   age_driving_licence <dbl>, fuel_type <chr>, vehicle_value <dbl>,\n#   seats <dbl>, power_to_weight_ratio <dbl>, vehicle_brand <chr>,\n#   municipality_type <chr>, circulation_area <chr>, total_premium <dbl>,\n#   liability_premium <dbl>, property_damage_premium <dbl>,\n#   theft_premium <dbl>, fire_premium <dbl>, glass_premium <dbl>, …\n```\n\n\n:::\n:::\n\n\nThe cleaned dataset retains **352,338 observations** — a reduction of only 1,802 rows (0.51%) from the original 354,140, confirming that the removal of missing values has minimal impact on the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"insured_id\"               \"year\"                    \n [3] \"policy_type\"              \"policy_status\"           \n [5] \"business_type\"            \"payment_frequency\"       \n [7] \"bonus_score\"              \"driver_age\"              \n [9] \"vehicle_age\"              \"age_driving_licence\"     \n[11] \"fuel_type\"                \"vehicle_value\"           \n[13] \"seats\"                    \"power_to_weight_ratio\"   \n[15] \"vehicle_brand\"            \"municipality_type\"       \n[17] \"circulation_area\"         \"total_premium\"           \n[19] \"liability_premium\"        \"property_damage_premium\" \n[21] \"theft_premium\"            \"fire_premium\"            \n[23] \"glass_premium\"            \"legal_protection_premium\"\n[25] \"occupants_premium\"        \"total_exposure\"          \n[27] \"liability_exposure\"       \"total_claims\"            \n[29] \"total_incurred\"          \n```\n\n\n:::\n:::\n\n\n## 4.3 Recoding Categorical Variables\n\n`recode()` is primarily used to replace specific values in a vector with new ones. The recoded variable is then assigned using `mutate()` of the **dplyr** package.\n\n::: panel-tabset\n## Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(policy_type = recode(policy_type,\n    \"TP\"     = \"Third-Party\",\n    \"TPG\"    = \"Third-Party with Glass\",\n    \"CC\"     = \"Third-Party Combined\",\n    \"COMP_E\" = \"Comprehensive with Excess\",\n    \"COMP_N\" = \"Comprehensive without Excess\"))\n```\n:::\n\n\n## Policy Status\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(policy_status = recode(policy_status,\n    \"A\" = \"Active\",\n    \"C\" = \"Cancelled\"))\n```\n:::\n\n\n## Business Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(business_type = recode(business_type,\n    \"NB\" = \"New Business\",\n    \"P\"  = \"Portfolio\"))\n```\n:::\n\n\n## Payment Frequency\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(payment_frequency = recode(payment_frequency,\n    \"A\" = \"Annual\",\n    \"S\" = \"Semi-Annual\",\n    \"Q\" = \"Quarterly\"))\n```\n:::\n\n\n## Bonus Score\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(bonus_score = recode(bonus_score,\n    \"G\" = \"Good\",\n    \"N\" = \"Neutral\",\n    \"B\" = \"Bad\"))\n```\n:::\n\n\n## Fuel Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(fuel_type = recode(fuel_type,\n    \"D\" = \"Diesel\",\n    \"G\" = \"Gasoline\"))\n```\n:::\n\n\n## Municipality Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(municipality_type = recode(municipality_type,\n    \"I\"  = \"Inland\",\n    \"C\"  = \"Coastal\",\n    \"IS\" = \"Islands\"))\n```\n:::\n\n\n## Circulation Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(circulation_area = recode(circulation_area,\n    \"U\" = \"Urban\",\n    \"R\" = \"Rural\"))\n```\n:::\n\n:::\n\n## 4.4 Data Type Conversion\n\nFrom the `glimpse()` output earlier, the categorical variables are currently stored as character (`chr`) data type. They need to be converted to **factors** (`fct`) so that R treats them correctly in visualisations and statistical analyses. `mutate()` and `as.factor()` of the **dplyr** package are used to perform the conversion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(policy_type       = as.factor(policy_type),\n         policy_status     = as.factor(policy_status),\n         business_type     = as.factor(business_type),\n         payment_frequency = as.factor(payment_frequency),\n         bonus_score       = as.factor(bonus_score),\n         fuel_type         = as.factor(fuel_type),\n         vehicle_brand     = as.factor(vehicle_brand),\n         municipality_type = as.factor(municipality_type),\n         circulation_area  = as.factor(circulation_area),\n         year              = as.factor(year),\n         seats             = as.factor(seats))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 352,338\nColumns: 29\n$ insured_id               <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, …\n$ year                     <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, 202…\n$ policy_type              <fct> Comprehensive with Excess, Comprehensive with…\n$ policy_status            <fct> Cancelled, Active, Active, Active, Active, Ac…\n$ business_type            <fct> New Business, Portfolio, Portfolio, Portfolio…\n$ payment_frequency        <fct> Annual, Annual, Annual, Annual, Semi-Annual, …\n$ bonus_score              <fct> Good, Good, Good, Good, Good, Good, Good, Goo…\n$ driver_age               <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39, 4…\n$ vehicle_age              <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20, 2…\n$ age_driving_licence      <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19, 1…\n$ fuel_type                <fct> Gasoline, Diesel, Diesel, Diesel, Diesel, Die…\n$ vehicle_value            <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5162…\n$ seats                    <fct> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio    <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.19, …\n$ vehicle_brand            <fct> PORSCHE, MERCEDES, MERCEDES, MERCEDES, KIA, K…\n$ municipality_type        <fct> Inland, Inland, Inland, Inland, Inland, Inlan…\n$ circulation_area         <fct> Urban, Urban, Urban, Urban, Rural, Rural, Rur…\n$ total_premium            <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 687.4…\n$ liability_premium        <dbl> 30.60232, 114.33336, 110.66689, 122.09253, 21…\n$ property_damage_premium  <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 354.8…\n$ theft_premium            <dbl> 112.361489, 80.784824, 83.521384, 107.886872,…\n$ fire_premium             <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.715…\n$ glass_premium            <dbl> 8.305788, 30.091751, 32.861626, 31.101584, 48…\n$ legal_protection_premium <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6.70…\n$ occupants_premium        <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827, 1…\n$ total_exposure           <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000000…\n$ liability_exposure       <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000000…\n$ total_claims             <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, …\n$ total_incurred           <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.000…\n```\n\n\n:::\n:::\n\n\n## 4.5 Variable Creation\n\nThree new variables are created to support the analysis of portfolio profitability and volatility. `mutate()` of the **dplyr** package is used to create these variables.\n\n### 4.5.1 Loss Ratio\n\n`loss_ratio` is calculated as the ratio of total incurred costs to total premium collected. A loss ratio greater than 1 indicates that the insurer paid out more in claims than it collected in premiums, reflecting poor profitability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(loss_ratio = total_incurred / total_premium)\n```\n:::\n\n\n### 4.5.2 Claim Frequency\n\n`claim_frequency` is calculated as the ratio of total claims to total exposure. It measures how often claims occur per policy year, reflecting the volatility of the portfolio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(claim_frequency = total_claims / total_exposure)\n```\n:::\n\n\n### 4.5.3 Has Claim\n\n`has_claim` is a binary indicator variable that takes the value 1 if a policy has at least one claim, and 0 otherwise. It is useful for identifying which policies have experienced a loss.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(has_claim = ifelse(total_claims > 0, 1, 0))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 352,338\nColumns: 32\n$ insured_id               <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, …\n$ year                     <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, 202…\n$ policy_type              <fct> Comprehensive with Excess, Comprehensive with…\n$ policy_status            <fct> Cancelled, Active, Active, Active, Active, Ac…\n$ business_type            <fct> New Business, Portfolio, Portfolio, Portfolio…\n$ payment_frequency        <fct> Annual, Annual, Annual, Annual, Semi-Annual, …\n$ bonus_score              <fct> Good, Good, Good, Good, Good, Good, Good, Goo…\n$ driver_age               <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39, 4…\n$ vehicle_age              <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20, 2…\n$ age_driving_licence      <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19, 1…\n$ fuel_type                <fct> Gasoline, Diesel, Diesel, Diesel, Diesel, Die…\n$ vehicle_value            <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5162…\n$ seats                    <fct> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio    <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.19, …\n$ vehicle_brand            <fct> PORSCHE, MERCEDES, MERCEDES, MERCEDES, KIA, K…\n$ municipality_type        <fct> Inland, Inland, Inland, Inland, Inland, Inlan…\n$ circulation_area         <fct> Urban, Urban, Urban, Urban, Rural, Rural, Rur…\n$ total_premium            <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 687.4…\n$ liability_premium        <dbl> 30.60232, 114.33336, 110.66689, 122.09253, 21…\n$ property_damage_premium  <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 354.8…\n$ theft_premium            <dbl> 112.361489, 80.784824, 83.521384, 107.886872,…\n$ fire_premium             <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.715…\n$ glass_premium            <dbl> 8.305788, 30.091751, 32.861626, 31.101584, 48…\n$ legal_protection_premium <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6.70…\n$ occupants_premium        <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827, 1…\n$ total_exposure           <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000000…\n$ liability_exposure       <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000000…\n$ total_claims             <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, …\n$ total_incurred           <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.000…\n$ loss_ratio               <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104, 0…\n$ claim_frequency          <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, …\n$ has_claim                <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n```\n\n\n:::\n:::\n\n\nThe dataset now contains **352,338 observations** across **32 variables**, with `loss_ratio`, `claim_frequency` and `has_claim` successfully added.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(insurance, \"insurance_clean.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- read_rds(\"insurance_clean.rds\")\n```\n:::\n\n\n# 5 Univariate Analysis\n\n## 5.1 Target Variables\n\nThe target variables are `loss_ratio`, `claim_frequency`, `total_incurred` and `has_claim`, which measure portfolio profitability, volatility, claim severity and claim occurrence respectively. As some variables contain extreme outliers, the analysis is restricted to a reasonable range for visualisation purposes. Before diving into the Exploratory Data Analysis, the distributions of key variables are examined individually to better understand their characteristics and identify any notable patterns.\n\n::: panel-tabset\n## Loss Ratio\n\n`loss_ratio` measures the ratio of total incurred costs to total premium collected. A loss ratio greater than 1 indicates that the insurer paid out more in claims than it collected in premiums.\n\nA raincloud plot is used here as it combines a half-violin density plot, boxplot and individual data points into a single view, providing a more complete picture of the distribution than a histogram or boxplot alone — simultaneously showing shape, central tendency, spread and outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_lr <- insurance %>%\n  filter(loss_ratio < 10,\n         loss_ratio > 0)\n\nggplot(insurance_lr,\n       aes(x = 0, y = loss_ratio)) +\n  stat_halfeye(adjust = 0.5,\n               justification = -0.2,\n               .width = 0,\n               point_colour = NA,\n               fill = \"#4a7c6f\") +\n  geom_boxplot(width = 0.2,\n               outlier.shape = NA,\n               fill = \"#7aadab\",\n               alpha = 0.5) +\n  coord_flip() +\n  labs(title = \"Distribution of Loss Ratio\",\n       subtitle = \"Policies with loss ratio between 0 and 10\",\n       x = NULL,\n       y = \"Loss Ratio\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe raincloud plot reveals that `loss_ratio` is highly right-skewed among policies with claims. Most policies record a loss ratio between 1.0 and 2.5, indicating that incurred costs typically exceed premiums collected. The long right tail suggests that a small number of policies experience exceptionally high losses, which significantly impacts overall portfolio profitability.\n\nA histogram paired with a boxplot is used below to complement the raincloud plot — the histogram reveals the precise frequency distribution while the boxplot highlights the median and interquartile range in a compact format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(insurance_lr,\n             aes(x = loss_ratio)) +\n  geom_histogram(binwidth = 0.1,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(loss_ratio)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(loss_ratio)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance_lr$loss_ratio) + 0.3,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean:\", round(mean(insurance_lr$loss_ratio), 2)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance_lr$loss_ratio) + 0.3,\n           y = Inf, vjust = 4,\n           label = paste(\"Median:\", round(median(insurance_lr$loss_ratio), 2)),\n           colour = \"blue\", size = 3) +\n  labs(title = \"Distribution of Loss Ratio\",\n       x = \"Loss Ratio\",\n       y = \"Count\") +\n  theme_minimal()\n\np2 <- ggplot(insurance_lr,\n             aes(x = loss_ratio,\n                 y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  labs(x = \"Loss Ratio\",\n       y = NULL) +\n  theme_minimal()\n\np2 / p1 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `loss_ratio` is highly right-skewed, with the majority of policies having a loss ratio of 0 (no claims made). The mean loss ratio is higher than the median, indicating the presence of a small number of policies with very high loss ratios that pull the mean upward.\n\n## Claim Frequency\n\n`claim_frequency` measures the ratio of total claims to total exposure. A higher claim frequency indicates greater volatility in the portfolio.\n\nA raincloud plot is used here for the same reasons as `loss_ratio` — combining density, boxplot and dot layers provides a richer distributional view than any single chart type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_cf <- insurance %>%\n  filter(claim_frequency < 10,\n         claim_frequency > 0)\n\nggplot(insurance_cf,\n       aes(x = 0, y = claim_frequency)) +\n  stat_halfeye(adjust = 0.5,\n               justification = -0.2,\n               .width = 0,\n               point_colour = NA,\n               fill = \"#4a7c6f\") +\n  geom_boxplot(width = 0.2,\n               outlier.shape = NA,\n               fill = \"#7aadab\",\n               alpha = 0.5) +\n  stat_dots(side = \"left\",\n            justification = 1.1,\n            binwidth = 0.05,\n            colour = \"#4a7c6f\",\n            alpha = 0.3) +\n  coord_flip() +\n  labs(title = \"Distribution of Claim Frequency\",\n       subtitle = \"Policies with claim frequency between 0 and 10\",\n       x = NULL,\n       y = \"Claim Frequency\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(insurance_cf,\n             aes(x = claim_frequency)) +\n  geom_histogram(binwidth = 0.1,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(claim_frequency)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(claim_frequency)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance_cf$claim_frequency) + 0.3,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean:\", round(mean(insurance_cf$claim_frequency), 2)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance_cf$claim_frequency) + 0.3,\n           y = Inf, vjust = 4,\n           label = paste(\"Median:\", round(median(insurance_cf$claim_frequency), 2)),\n           colour = \"blue\", size = 3) +\n  labs(title = \"Distribution of Claim Frequency\",\n       x = \"Claim Frequency\",\n       y = \"Count\") +\n  theme_minimal()\n\np4 <- ggplot(insurance_cf,\n             aes(x = claim_frequency,\n                 y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  labs(x = \"Claim Frequency\",\n       y = NULL) +\n  theme_minimal()\n\np4 / p3 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `claim_frequency` is heavily right-skewed, with most policies recording a claim frequency of around 1, meaning one claim per policy year. The mean of 1.95 is noticeably higher than the median of 1.28, driven by a small number of high-frequency claimants. The boxplot reveals numerous outliers beyond the upper whisker, indicating that a subset of policies experience a disproportionately high number of claims, contributing significantly to portfolio volatility.\n:::\n\n## Total Incurred\n\n`total_incurred` represents the total incurred cost of claims for each policy, including paid amounts and outstanding reserves. Only policies with claims are included in this analysis.\n\nA raincloud plot is used here as it effectively communicates both the density shape and the spread of claim costs, making it easier to identify skewness and outliers simultaneously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_ti <- insurance %>%\n  filter(total_incurred > 0,\n         total_incurred < 10000)\n\nggplot(insurance_ti,\n       aes(x = 0, y = total_incurred)) +\n  stat_halfeye(adjust = 0.5,\n               justification = -0.2,\n               .width = 0,\n               point_colour = NA,\n               fill = \"#4a7c6f\") +\n  geom_boxplot(width = 0.2,\n               outlier.shape = NA,\n               fill = \"#7aadab\",\n               alpha = 0.5) +\n  stat_dots(side = \"left\",\n            justification = 1.1,\n            binwidth = 50,\n            colour = \"#4a7c6f\",\n            alpha = 0.3) +\n  coord_flip() +\n  labs(title = \"Distribution of Total Incurred\",\n       subtitle = \"Policies with total incurred between €0 and €10,000\",\n       x = NULL,\n       y = \"Total Incurred (€)\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n## ECDF of Incurred Amount by Policy Type \n\nAn Empirical Cumulative Distribution Function (ECDF) plot is used below to complement the histogram. Unlike a histogram where the shape can change depending on bin width, the ECDF makes no such assumption, it shows directly what proportion of claims fall below any given cost level for each policy type, making it easier to compare tail behaviour across groups at a glance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  filter(total_incurred > 0, total_incurred < 10000) %>%\n  ggplot(aes(x = total_incurred, colour = policy_type)) +\n  stat_ecdf(linewidth = 0.8) +\n  scale_x_continuous(labels = scales::comma) +\n  scale_colour_manual(values = c(\n    \"Comprehensive with Excess\"    = \"#4a7c6f\",\n    \"Comprehensive without Excess\" = \"#7aadab\",\n    \"Third-Party\"                  = \"#d4e8e1\",\n    \"Third-Party Combined\"         = \"#2d5a51\",\n    \"Third-Party with Glass\"       = \"#a8d5c2\")) +\n  labs(title = \"ECDF of Total Incurred by Policy Type\",\n       subtitle = \"Policies with total incurred between €0 and €10,000\",\n       x = \"Total Incurred (€)\",\n       y = \"Cumulative Proportion\",\n       colour = \"Policy Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\nThe ECDF plot shows that all five policy types follow a broadly similar distribution, with most claims concentrated below €2,500. **Third-Party with Glass** and **Comprehensive without Excess** curves rise more steeply in the lower cost range, indicating a higher proportion of small, cheap claims, consistent with the finding that the absence of an excess encourages filing of minor claims. **Comprehensive with Excess** and **Third-Party Combined** have slightly flatter curves, suggesting a wider spread of claim costs including a larger proportion of mid-to-high cost claims. **Third-Party** shows the most gradual curve, indicating the greatest spread of claim costs across the full range though its small sample size means this should be interpreted with caution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- ggplot(insurance_ti,\n             aes(x = total_incurred)) +\n  geom_histogram(binwidth = 200,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(total_incurred)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(total_incurred)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance_ti$total_incurred) + 500,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean: €\", round(mean(insurance_ti$total_incurred), 2)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance_ti$total_incurred) + 500,\n           y = Inf, vjust = 4,\n           label = paste(\"Median: €\", round(median(insurance_ti$total_incurred), 2)),\n           colour = \"blue\", size = 3) +\n  labs(title = \"Distribution of Total Incurred\",\n       x = \"Total Incurred (€)\",\n       y = \"Count\") +\n  theme_minimal()\n\np6 <- ggplot(insurance_ti,\n             aes(x = total_incurred,\n                 y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  labs(x = \"Total Incurred (€)\",\n       y = NULL) +\n  theme_minimal()\n\np6 / p5 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `total_incurred` is moderately right-skewed, with most policies recording claim costs below €2,500. The mean of €1,271.98 is higher than the median of €898.68, indicating that a small number of high-cost claims pull the average upward. Overall, the majority of claims are relatively manageable in size, though the long tail suggests that occasional large claims do occur within the portfolio.\n\n## Has Claim\n\n`has_claim` is a binary variable indicating whether a policy has recorded at least one claim (1) or no claims (0). A bar chart is used here as it is the most appropriate chart type for a binary categorical variable — directly showing the count and proportion of each group without implying any ordering or magnitude between them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  mutate(has_claim = ifelse(has_claim == 1,\n                            \"Has Claim\",\n                            \"No Claim\")) %>%\n  count(has_claim) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = has_claim,\n             y = n,\n             fill = has_claim)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_fill_manual(values = c(\"Has Claim\" = \"#4a7c6f\",\n                                \"No Claim\" = \"#7aadab\")) +\n  labs(title = \"Distribution of Claim Occurrence\",\n       x = NULL,\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **85.7%** of policies in the portfolio have not recorded any claims, while only **14.3%** have experienced at least one claim. This is typical of motor insurance portfolios where most policyholders do not make a claim in a given year. Despite being a small proportion, the 14.3% of policies with claims are of particular interest as they are the primary drivers of portfolio profitability and volatility.\n\n## 5.2 Driver Characteristics\n\nThis section explores the distribution of driver-related variables in the portfolio, specifically `driver_age` and `bonus_score`.\n\n::: panel-tabset\n## Driver Age\n\n`driver_age` represents the age of the main driver associated with each policy, measured in years. A histogram paired with a boxplot is used here — the histogram reveals the shape and spread of the age distribution, while the boxplot succinctly shows the median and interquartile range and flags any extreme outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np7 <- ggplot(insurance,\n             aes(x = driver_age)) +\n  geom_histogram(binwidth = 1,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(driver_age)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(driver_age)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance$driver_age) + 4,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean:\", round(mean(insurance$driver_age), 1)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance$driver_age) + 4,\n           y = Inf, vjust = 4,\n           label = paste(\"Median:\", round(median(insurance$driver_age), 1)),\n           colour = \"blue\", size = 3) +\n  labs(title = \"Distribution of Driver Age\",\n       x = \"Driver Age (years)\",\n       y = \"Count\") +\n  theme_minimal()\n\np8 <- ggplot(insurance,\n             aes(x = driver_age,\n                 y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  labs(x = \"Driver Age (years)\",\n       y = NULL) +\n  theme_minimal()\n\np8 / p7 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `driver_age` is approximately bell-shaped and slightly right-skewed, with most drivers aged between 35 and 65 years. The mean age of 49 and median of 48 are very close, confirming a relatively symmetric distribution. The boxplot shows that the middle 50% of drivers fall between approximately 39 and 58 years old, with a small number of older drivers above 75 appearing as outliers.\n\n## Bonus Score\n\n`bonus_score` reflects the policyholder's past claims experience — Good (G), Neutral (N) or Bad (B). A bar chart is used here as it is the most suitable chart type for an ordinal categorical variable with a small number of levels, making proportional differences easy to compare at a glance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(bonus_score) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(bonus_score, -n),\n             y = n,\n             fill = bonus_score)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Good\"    = \"#4a7c6f\",\n                                \"Neutral\" = \"#7aadab\",\n                                \"Bad\"     = \"#d4e8e1\")) +\n  labs(title = \"Distribution of Bonus Score\",\n       x = \"Bonus Score\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **96.5%** of policies belong to policyholders with a Good bonus score, indicating a strong claims history across the portfolio. Only **2.2%** are Neutral and **1.3%** are Bad. This suggests that the portfolio is largely made up of low-risk, experienced policyholders who have rarely or never made a claim.\n:::\n\n## 5.3 Vehicle Characteristics\n\nThis section explores the distribution of vehicle-related variables in the portfolio, specifically `vehicle_age`, `vehicle_value`, `fuel_type` and `vehicle_brand`.\n\n::: panel-tabset\n## Vehicle Age\n\n`vehicle_age` represents the age of the insured vehicle in years. A histogram and boxplot combination is used here for the same reasons as `driver_age` — the histogram reveals the shape and spread of the age distribution, while the boxplot highlights central tendency and outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np9 <- ggplot(insurance,\n             aes(x = vehicle_age)) +\n  geom_histogram(binwidth = 1,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(vehicle_age)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(vehicle_age)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance$vehicle_age) + 5,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean:\", round(mean(insurance$vehicle_age), 1)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance$vehicle_age) + 5,\n           y = Inf, vjust = 4,\n           label = paste(\"Median:\", round(median(insurance$vehicle_age), 1)),\n           colour = \"blue\", size = 3) +\n  labs(title = \"Distribution of Vehicle Age\",\n       x = \"Vehicle Age (years)\",\n       y = \"Count\") +\n  theme_minimal()\n\np10 <- ggplot(insurance,\n              aes(x = vehicle_age,\n                  y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  labs(x = \"Vehicle Age (years)\",\n       y = NULL) +\n  theme_minimal()\n\np10 / p9 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `vehicle_age` is approximately bell-shaped, with most vehicles aged between 15 and 40 years. The mean of 25.9 years and median of 25 years are very close together, confirming a relatively symmetric distribution. This suggests that the portfolio is dominated by older vehicles, which may reflect the nature of the Spanish non-life insurance market. The boxplot reveals a small number of very old vehicles (over 55 years) appearing as outliers.\n\n## Vehicle Value\n\n`vehicle_value` represents the declared insured value of the vehicle in euros. A histogram and boxplot combination is used here as `vehicle_value` is a continuous numerical variable — the histogram reveals the distribution shape and the location of the mode, while the boxplot highlights the extent of outliers in the upper tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np11 <- ggplot(insurance,\n              aes(x = vehicle_value)) +\n  geom_histogram(binwidth = 2000,\n                 fill = \"#4a7c6f\",\n                 colour = \"white\") +\n  geom_vline(aes(xintercept = mean(vehicle_value)),\n             colour = \"red\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  geom_vline(aes(xintercept = median(vehicle_value)),\n             colour = \"blue\",\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  annotate(\"text\", x = mean(insurance$vehicle_value) + 20000,\n           y = Inf, vjust = 2,\n           label = paste(\"Mean: €\", round(mean(insurance$vehicle_value), 0)),\n           colour = \"red\", size = 3) +\n  annotate(\"text\", x = median(insurance$vehicle_value) + 20000,\n           y = Inf, vjust = 4,\n           label = paste(\"Median: €\", round(median(insurance$vehicle_value), 0)),\n           colour = \"blue\", size = 3) +\n  scale_x_continuous(labels = scales::comma) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of Vehicle Value\",\n       x = \"Vehicle Value (€)\",\n       y = \"Count\") +\n  theme_minimal()\n\np12 <- ggplot(insurance,\n              aes(x = vehicle_value,\n                  y = \"\")) +\n  geom_boxplot(fill = \"#7aadab\",\n               outlier.alpha = 0.3,\n               outlier.size = 0.5) +\n  scale_x_continuous(labels = scales::comma) +\n  labs(x = \"Vehicle Value (€)\",\n       y = NULL) +\n  theme_minimal()\n\np12 / p11 +\n  plot_layout(heights = c(1, 3.5))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nThe distribution of `vehicle_value` is highly right-skewed, with the majority of vehicles valued below €50,000. The mean of €26,937 is slightly higher than the median of €24,687, indicating that a small number of high-value vehicles are pulling the average upward. The boxplot confirms the presence of numerous extreme outliers stretching beyond €200,000, likely representing luxury or high-performance vehicles.\n\n## Fuel Type\n\n`fuel_type` indicates whether the vehicle runs on Diesel or Gasoline. A bar chart is used here as `fuel_type` is a binary categorical variable — a bar chart directly compares the count and proportion of each group without implying any quantitative scale between them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(fuel_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(fuel_type, -n),\n             y = n,\n             fill = fuel_type)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Diesel\"   = \"#4a7c6f\",\n                                \"Gasoline\" = \"#7aadab\")) +\n  labs(title = \"Distribution of Fuel Type\",\n       x = \"Fuel Type\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **64.2%** of policies are associated with Diesel vehicles, while **35.8%** are Gasoline. The predominance of diesel vehicles reflects the historically strong preference for diesel cars in the Spanish market, particularly for older vehicles which make up a large proportion of this portfolio.\n\n## Vehicle Brand\n\n`vehicle_brand` represents the brand of the insured vehicle. As there are 65 brands in the dataset, only the top 10 most common brands are shown for clarity. A horizontal bar chart is used here as it is the most appropriate chart type for a categorical variable with many levels — the horizontal orientation prevents label overlap and the ranking order makes comparisons intuitive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(vehicle_brand) %>%\n  arrange(desc(n)) %>%\n  slice_head(n = 10) %>%\n  mutate(pct = n / sum(insurance %>% count(vehicle_brand) %>% pull(n)) * 100) %>%\n  ggplot(aes(x = reorder(vehicle_brand, n),\n             y = n)) +\n  geom_col(fill = \"#4a7c6f\") +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            hjust = -0.1,\n            size = 3) +\n  scale_y_continuous(labels = scales::comma) +\n  coord_flip() +\n  labs(title = \"Top 10 Vehicle Brands by Number of Policies\",\n       x = \"Vehicle Brand\",\n       y = \"Number of Policies\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that Renault (**9.7%**), Citroen (**9.2%**) and Peugeot (**8.4%**) are the three most common vehicle brands in the portfolio, reflecting the strong presence of French automobile brands in the Spanish market. The top 7 brands are all European, with SEAT being the only Spanish brand in the list. Toyota is the only Asian brand to appear in the top 10, ranking last with **4%** of policies.\n:::\n\n## 5.4 Policy Characteristics\n\nThis section explores the distribution of policy-related variables in the portfolio, specifically `policy_type`, `policy_status`, `business_type` and `payment_frequency`.\n\n::: panel-tabset\n## Policy Type\n\n`policy_type` describes the main coverage structure of the motor insurance policy. An interactive bar chart using `ggiraph` is used here — it allows users to hover over each bar to see the exact count and proportion, which is useful given the number of policy types and the varying label lengths.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_interactive <- insurance %>%\n  count(policy_type) %>%\n  mutate(pct = n / sum(n) * 100,\n         tooltip = paste0(policy_type, \"\\n\",\n                          \"Count: \", scales::comma(n), \"\\n\",\n                          \"Share: \", round(pct, 1), \"%\")) %>%\n  ggplot(aes(x = reorder(policy_type, -n),\n             y = n,\n             tooltip = tooltip,\n             data_id = policy_type)) +\n  geom_col_interactive(fill = \"#4a7c6f\") +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of Policy Type\",\n       x = \"Policy Type\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        axis.text.x = element_text(angle = 15, hjust = 1))\n\ngirafe(ggobj = p_interactive,\n       width_svg = 8,\n       height_svg = 4)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-e83a18dbaf594382d3b1\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e83a18dbaf594382d3b1\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_fbb6e2d18ad41e27' viewBox='0 0 576 288'>\\n <defs id='svg_fbb6e2d18ad41e27_defs'>\\n  <clipPath id='svg_fbb6e2d18ad41e27_c1'>\\n   <rect x='0' y='0' width='576' height='288'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_fbb6e2d18ad41e27_c2'>\\n   <rect x='54.82' y='22.77' width='515.7' height='202.84'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_fbb6e2d18ad41e27_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_fbb6e2d18ad41e27_c1)'>\\n   <rect x='0' y='0' width='576' height='288' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n   <rect x='0' y='0' width='576' height='288' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_fbb6e2d18ad41e27_c2)'>\\n   <polyline points='54.82,193.82 570.52,193.82' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,148.70 570.52,148.70' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,103.57 570.52,103.57' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,58.45 570.52,58.45' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,216.39 570.52,216.39' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,171.26 570.52,171.26' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,126.14 570.52,126.14' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,81.01 570.52,81.01' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='54.82,35.88 570.52,35.88' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='114.33,225.61 114.33,22.77' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='213.50,225.61 213.50,22.77' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='312.67,225.61 312.67,22.77' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='411.84,225.61 411.84,22.77' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='511.02,225.61 511.02,22.77' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_fbb6e2d18ad41e27_e1' x='168.87' y='134.87' width='89.26' height='81.52' fill='#4A7C6F' fill-opacity='1' stroke='none' title='Comprehensive with Excess&amp;lt;br/&amp;gt;Count: 90,320&amp;lt;br/&amp;gt;Share: 25.6%' data-id='Comprehensive with Excess'/>\\n   <rect id='svg_fbb6e2d18ad41e27_e2' x='367.22' y='201.94' width='89.26' height='14.45' fill='#4A7C6F' fill-opacity='1' stroke='none' title='Comprehensive without Excess&amp;lt;br/&amp;gt;Count: 16,012&amp;lt;br/&amp;gt;Share: 4.5%' data-id='Comprehensive without Excess'/>\\n   <rect id='svg_fbb6e2d18ad41e27_e3' x='466.39' y='211.24' width='89.26' height='5.15' fill='#4A7C6F' fill-opacity='1' stroke='none' title='Third-Party&amp;lt;br/&amp;gt;Count: 5,701&amp;lt;br/&amp;gt;Share: 1.6%' data-id='Third-Party'/>\\n   <rect id='svg_fbb6e2d18ad41e27_e4' x='69.7' y='31.99' width='89.26' height='184.4' fill='#4A7C6F' fill-opacity='1' stroke='none' title='Third-Party Combined&amp;lt;br/&amp;gt;Count: 204,317&amp;lt;br/&amp;gt;Share: 58%' data-id='Third-Party Combined'/>\\n   <rect id='svg_fbb6e2d18ad41e27_e5' x='268.04' y='183.91' width='89.26' height='32.48' fill='#4A7C6F' fill-opacity='1' stroke='none' title='Third-Party with Glass&amp;lt;br/&amp;gt;Count: 35,988&amp;lt;br/&amp;gt;Share: 10.2%' data-id='Third-Party with Glass'/>\\n   <text x='197.37' y='130.96' font-size='8.54pt' font-family='Liberation Sans'>25.6%<\\/text>\\n   <text x='398.88' y='198.02' font-size='8.54pt' font-family='Liberation Sans'>4.5%<\\/text>\\n   <text x='498.05' y='207.33' font-size='8.54pt' font-family='Liberation Sans'>1.6%<\\/text>\\n   <text x='102.94' y='28.07' font-size='8.54pt' font-family='Liberation Sans'>58%<\\/text>\\n   <text x='296.54' y='179.99' font-size='8.54pt' font-family='Liberation Sans'>10.2%<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_fbb6e2d18ad41e27_c1)'>\\n   <text x='45' y='219.42' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='22.96' y='174.29' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>50,000<\\/text>\\n   <text x='18.07' y='129.16' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>100,000<\\/text>\\n   <text x='18.07' y='84.04' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>150,000<\\/text>\\n   <text x='18.07' y='38.91' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>200,000<\\/text>\\n   <text transform='translate(32.75,258.67) rotate(-15.00)' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>Third-Party Combined<\\/text>\\n   <text transform='translate(108.30,265.00) rotate(-15.00)' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>Comprehensive with Excess<\\/text>\\n   <text transform='translate(230.64,258.79) rotate(-15.00)' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>Third-Party with Glass<\\/text>\\n   <text transform='translate(294.82,268.16) rotate(-15.00)' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>Comprehensive without Excess<\\/text>\\n   <text transform='translate(470.55,247.65) rotate(-15.00)' font-size='6.6pt' font-family='Liberation Sans' fill='#4D4D4D' fill-opacity='1'>Third-Party<\\/text>\\n   <text x='284.65' y='280.24' font-size='8.25pt' font-family='Liberation Sans'>Policy Type<\\/text>\\n   <text transform='translate(13.05,170.35) rotate(-90.00)' font-size='8.25pt' font-family='Liberation Sans'>Number of Policies<\\/text>\\n   <text x='54.82' y='14.55' font-size='9.9pt' font-family='Liberation Sans'>Distribution of Policy Type<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_fbb6e2d18ad41e27\",\"ratio\":2,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:9999;}\",\"placement\":\"doc\",\"opacity\":0.9,\"offx\":10,\"offy\":10,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_data_SVGID_ { stroke:orange; }\",\"reactive\":true,\"nearest_distance\":null,\"linked\":false},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_data_SVGID_ { stroke:none;fill:red; }\\ncircle.select_data_SVGID_ { fill:red;stroke:black; }\\nline.select_data_SVGID_, polyline.select_data_SVGID_ { fill:none;stroke:red; }\\nrect.select_data_SVGID_, polygon.select_data_SVGID_, path.select_data_SVGID_ { fill:red;stroke:none; }\\nimage.select_data_SVGID_ { stroke:red; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[],\"linked\":false},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":1,\"duration\":300,\"default_on\":false},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThe bar chart shows that Third-Party Combined policies account for the largest share of the portfolio at **58%**, followed by Comprehensive with Excess at **25.6%**. Third-Party with Glass (**10.2%**) and Comprehensive without Excess (**4.5%**) make up smaller proportions, while basic Third-Party policies are the least common at only **1.6%**. The dominance of Third-Party Combined policies suggests that most policyholders opt for broader coverage beyond basic liability, combining theft, fire and glass protection in a single policy.\n\n## Policy Status\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(policy_status) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(policy_status, -n),\n             y = n,\n             fill = policy_status)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Active\"    = \"#4a7c6f\",\n                                \"Cancelled\" = \"#7aadab\")) +\n  labs(title = \"Distribution of Policy Status\",\n       x = \"Policy Status\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **89.2%** of policies are Active, while **10.8%** have been Cancelled. The low cancellation rate suggests a relatively stable and loyal customer base within the portfolio.\n\n## Business Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(business_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(business_type, -n),\n             y = n,\n             fill = business_type)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"New Business\" = \"#4a7c6f\",\n                                \"Portfolio\"    = \"#7aadab\")) +\n  labs(title = \"Distribution of Business Type\",\n       x = \"Business Type\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **69.3%** of policies are New Business, while **30.7%** are Portfolio renewals. The higher proportion of new business suggests that the insurer has been actively growing its customer base during the period covered by the dataset.\n\n## Payment Frequency\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(payment_frequency) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(payment_frequency, -n),\n             y = n,\n             fill = payment_frequency)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Annual\"      = \"#4a7c6f\",\n                                \"Semi-Annual\" = \"#7aadab\",\n                                \"Quarterly\"   = \"#d4e8e1\")) +\n  labs(title = \"Distribution of Payment Frequency\",\n       x = \"Payment Frequency\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **81.3%** of policies are billed Annually, followed by Semi-Annual (**14.4%**) and Quarterly (**4.3%**). The overwhelming preference for annual billing suggests that most policyholders are comfortable committing to a full year of coverage upfront.\n:::\n\n## 5.5 Geographic Characteristics\n\nThis section explores the distribution of geographic variables in the portfolio, specifically `municipality_type` and `circulation_area`.\n\n::: panel-tabset\n## Municipality Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(municipality_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(municipality_type, -n),\n             y = n,\n             fill = municipality_type)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Inland\"  = \"#4a7c6f\",\n                                \"Coastal\" = \"#7aadab\",\n                                \"Islands\" = \"#d4e8e1\")) +\n  labs(title = \"Distribution of Municipality Type\",\n       x = \"Municipality Type\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.margin = margin(t = 30))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **64.6%** of policies are from Inland municipalities, followed by Coastal (**28.6%**) and Islands (**6.8%**). This reflects the geographic distribution of the Spanish population, where most people live in inland cities such as Madrid.\n\n## Circulation Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  count(circulation_area) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(circulation_area, -n),\n             y = n,\n             fill = circulation_area)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            vjust = -0.5,\n            size = 4) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(values = c(\"Urban\" = \"#4a7c6f\",\n                                \"Rural\" = \"#7aadab\")) +\n  labs(title = \"Distribution of Circulation Area\",\n       x = \"Circulation Area\",\n       y = \"Number of Policies\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.margin = margin(t = 30))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows that **53.8%** of policies are associated with Urban circulation, while **46.2%** are Rural. Urban drivers tend to face higher traffic density, which may lead to more frequent but less severe claims, while rural drivers may experience fewer but potentially more severe accidents due to higher speeds.\n:::\n\n# 6 Exploratory Data Analysis\n\nIn this section, bivariate visual analytics techniques are applied to investigate and statistically validate the factors influencing the profitability and volatility of the motor insurance portfolio.\n\n## 6.1 Year-on-Year Loss Ratio Trend\n\nA line chart is used here as it is the most appropriate chart type for communicating directional trends over time — making it easy to identify whether portfolio profitability is improving or deteriorating across the three-year period. The break-even line at 1.0 provides an immediate visual reference point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  group_by(year) %>%\n  summarise(\n    loss_ratio    = sum(total_incurred) / sum(total_premium),\n    claim_freq    = sum(total_claims) / sum(total_exposure)\n  ) %>%\n  ggplot(aes(x = year, group = 1)) +\n  geom_line(aes(y = loss_ratio), colour = \"#4a7c6f\", linewidth = 1.2) +\n  geom_point(aes(y = loss_ratio), colour = \"#4a7c6f\", size = 3) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"red\") +\n  geom_text(aes(y = loss_ratio,\n                label = round(loss_ratio, 3)),\n            vjust = -0.8, size = 3) +\n  labs(title = \"Portfolio Loss Ratio by Year\",\n       subtitle = \"Red dashed line = break-even (loss ratio = 1.0)\",\n       x = \"Year\",\n       y = \"Loss Ratio\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThe line chart reveals how the portfolio loss ratio has evolved over the 2022–2024 period. The portfolio loss ratio has been rising steadily from **0.657 in 2022** to **0.665 in 2023** and **0.747 in 2024**. While the portfolio remains below the break-even line of 1.0, meaning the insurer is still profitable overall the upward trend is a concern. If this trend continues, the portfolio could approach or breach the break-even point in future years, making it important to investigate and address the underlying loss drivers now.\n\n## 6.2 Bubble Chart: Severity, Frequency and Premium Volume\n\nA bubble chart is used here to simultaneously visualise three dimensions — average claim severity, claim frequency and premium volume — across policy types. This provides a more complete picture of risk concentration than any single measure alone, allowing the identification of segments that are simultaneously high risk and low premium.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  filter(has_claim == 1) %>%\n  group_by(policy_type) %>%\n  summarise(\n    avg_severity  = mean(total_incurred),\n    avg_frequency = mean(claim_frequency),\n    total_premium = sum(total_premium),\n    n = n()\n  ) %>%\n  ggplot(aes(x = avg_frequency,\n             y = avg_severity,\n             size = total_premium,\n             colour = policy_type,\n             label = policy_type)) +\n  geom_point(alpha = 0.7) +\n  ggrepel::geom_text_repel(size = 3,\n                            box.padding = 0.5,\n                            point.padding = 0.3) +\n  scale_size_continuous(range = c(3, 15),\n                        labels = scales::comma) +\n  scale_x_continuous(labels = scales::comma,\n                     expand = expansion(mult = 0.2)) +\n  scale_y_continuous(labels = scales::comma,\n                     expand = expansion(mult = 0.2)) +\n  scale_colour_manual(values = c(\n    \"Comprehensive with Excess\"    = \"#4a7c6f\",\n    \"Comprehensive without Excess\" = \"#7aadab\",\n    \"Third-Party\"                  = \"#d4e8e1\",\n    \"Third-Party Combined\"         = \"#2d5a51\",\n    \"Third-Party with Glass\"       = \"#a8d5c2\")) +\n  labs(title = \"Severity vs Frequency by Policy Type\",\n       subtitle = \"Bubble size = total premium volume\",\n       x = \"Average Claim Frequency\",\n       y = \"Average Claim Severity (€)\",\n       size = \"Total Premium (€)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nThe bubble chart shows that Comprehensive without Excess policies have the highest claim frequency and highest severity but the premiums collected from this group are relatively low. This means the insurer is likely losing money on this segment.Third-Party Combined is the largest segment by premium volume, but policyholders claim very frequently. The saving grace is that individual claims tend to be cheaper. Comprehensive with Excess is the healthiest segment, claims are less frequent, and the large premium volume means the insurer is well-positioned to cover losses. Third-Party and Third-Party with Glass are small segments with minimal impact on the overall portfolio.\n\n## 6.3 Factors Affecting Loss Ratio (Profitability)\n\n`loss_ratio` is used as the measure of portfolio profitability. Only policies with a loss ratio between 0 and 10 are included to exclude extreme outliers that may distort the analysis.\n\n`ggbetweenstats()` of the **ggstatsplot** package is used throughout this section as it integrates the visual comparison of group distributions with the results of a nonparametric statistical test in a single figure. The nonparametric Kruskal-Wallis test is chosen because `loss_ratio` is non-normally distributed and right-skewed, violating the normality assumption required for ANOVA.\n\n::: panel-tabset\n## Bonus Score\n\nThe violin plot below examines whether `bonus_score` — reflecting a policyholder's past claims history — has a significant effect on `loss_ratio`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_lr,\n  x    = bonus_score,\n  y    = loss_ratio,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Loss Ratio by Bonus Score\",\n  xlab = \"Bonus Score\",\n  ylab = \"Loss Ratio\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference in loss ratio across bonus score groups (p = 2.07e-19). Interestingly, policyholders with a **Good** bonus score have the highest median loss ratio of **2.02**, followed by **Neutral** (1.60) and **Bad** (1.44). This counterintuitive finding may be attributed to the fact that Good bonus score policyholders dominate the portfolio (n = 35,663) and tend to hold more comprehensive policies, which attract higher claim costs. All pairwise comparisons are statistically significant, confirming that bonus score is a meaningful differentiator of portfolio profitability.\n\n## Policy Type\n\nThe violin plot below examines whether `policy_type` has a significant effect on `loss_ratio`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_lr,\n  x    = policy_type,\n  y    = loss_ratio,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Loss Ratio by Policy Type\",\n  xlab = \"Policy Type\",\n  ylab = \"Loss Ratio\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference in loss ratio across policy types (p = 5.09e-92). The **Third-Party** policy type has the highest median loss ratio of **4.29** (n = 241), which is notably higher than all other policy types. Among the remaining policy types, **Third-Party Combined** (2.25) and **Third-Party with Glass** (2.22) have higher median loss ratios compared to **Comprehensive with Excess** (1.74) and **Comprehensive without Excess** (1.78).\n\n## Fuel Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_lr,\n  x    = fuel_type,\n  y    = loss_ratio,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Loss Ratio by Fuel Type\",\n  xlab = \"Fuel Type\",\n  ylab = \"Loss Ratio\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nThe Mann-Whitney test confirms a statistically significant difference in loss ratio between fuel types (p = 3.48e-26). Gasoline vehicles have a higher median loss ratio of **2.22** compared to Diesel at **1.92**. Although the effect size is small (r = -0.07), the difference is statistically significant.\n\n## Circulation Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_lr,\n  x    = circulation_area,\n  y    = loss_ratio,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Loss Ratio by Circulation Area\",\n  xlab = \"Circulation Area\",\n  ylab = \"Loss Ratio\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nThe Mann-Whitney test confirms a statistically significant difference (p = 2.68e-07). **Rural** drivers have a slightly higher median loss ratio of **2.06** compared to **Urban** drivers at **1.95**. However, the effect size is very small (r = 0.03), suggesting that while statistically significant, circulation area is not practically meaningful as a standalone profitability driver.\n\n## Driver Age\n\nThe scatterplot below uses `ggscatterstats()` as it is the most appropriate visualisation for examining the relationship between two continuous variables — it simultaneously shows the scatter of individual data points, the regression trend line, and the Spearman correlation test result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatterstats(\n  data = insurance_lr,\n  x    = driver_age,\n  y    = loss_ratio,\n  type = \"nonparametric\",\n  messages = FALSE,\n  title = \"Loss Ratio by Driver Age\",\n  xlab = \"Driver Age (years)\",\n  ylab = \"Loss Ratio\",\n  marginal = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nThe Spearman correlation test reveals a statistically significant but very weak positive relationship (ρ = 0.03, p = 1.00e-07). The nearly flat trend line confirms that driver age alone is not a strong predictor of portfolio profitability.\n:::\n\n## 6.4 Factors Affecting Claim Frequency (Volatility)\n\n`claim_frequency` is used as the measure of portfolio volatility. Only policies with a claim frequency between 0 and 10 are included to exclude extreme outliers. The same nonparametric approach is used here as `claim_frequency` is similarly right-skewed and non-normally distributed.\n\n::: panel-tabset\n## Bonus Score\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_cf,\n  x    = bonus_score,\n  y    = claim_frequency,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Claim Frequency by Bonus Score\",\n  xlab = \"Bonus Score\",\n  ylab = \"Claim Frequency\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference in claim frequency across bonus score groups (p = 8.47e-61). As expected, policyholders with a **Bad** bonus score have the highest median claim frequency of **1.98** (n = 999), followed by **Neutral** (1.81, n = 1,333) and **Good** (1.26, n = 47,383). This pattern confirms that past claims history is a reliable indicator of future claim behaviour. All pairwise comparisons are statistically significant.\n\n## Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_cf,\n  x    = policy_type,\n  y    = claim_frequency,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Claim Frequency by Policy Type\",\n  xlab = \"Policy Type\",\n  ylab = \"Claim Frequency\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference (p = 3.28e-298). **Comprehensive without Excess** policies have the highest median claim frequency of **2.00** (n = 4,836). This suggests that the absence of an excess removes the financial disincentive to file small claims. All pairwise comparisons are statistically significant.\n\n## Municipality Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_cf,\n  x    = municipality_type,\n  y    = claim_frequency,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Claim Frequency by Municipality Type\",\n  xlab = \"Municipality Type\",\n  ylab = \"Claim Frequency\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference (p = 6.41e-05). However, the effect size is negligible, suggesting that municipality type has minimal practical impact on claim frequency.\n\n## Circulation Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_cf,\n  x    = circulation_area,\n  y    = claim_frequency,\n  type = \"nonparametric\",\n  mean.ci = TRUE,\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  p.adjust.method = \"fdr\",\n  messages = FALSE,\n  title = \"Claim Frequency by Circulation Area\",\n  xlab = \"Circulation Area\",\n  ylab = \"Claim Frequency\",\n  palette = \"Set2\"\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\nThe Mann-Whitney test confirms a statistically significant difference (p = 4.86e-13). **Urban** drivers have a higher median claim frequency of **1.33** compared to **Rural** drivers at **1.23**, consistent with the higher traffic density in urban environments. However, the effect size is small (r = -0.04).\n\n## Driver Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatterstats(\n  data = insurance_cf,\n  x    = driver_age,\n  y    = claim_frequency,\n  type = \"nonparametric\",\n  messages = FALSE,\n  title = \"Claim Frequency by Driver Age\",\n  xlab = \"Driver Age (years)\",\n  ylab = \"Claim Frequency\",\n  marginal = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\nThe Spearman correlation test reveals a statistically significant but very weak negative relationship (ρ = -0.04, p = 3.07e-20). Driver age alone is not a meaningful predictor of portfolio volatility in this dataset.\n:::\n\n## 6.5 Distribution Comparison across Key Groups\n\nTo complement the statistical analysis in Sections 6.3 and 6.4, ridgeline plots are used to compare the full distribution of `loss_ratio` and `claim_frequency` across key grouping variables. Ridgeline plots are chosen here as they allow simultaneous comparison of full distribution shapes across multiple groups — revealing modality, skewness and tail behaviour that boxplots alone cannot convey.\n\n::: panel-tabset\n## Loss Ratio by Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_lr %>%\n  ggplot(aes(x = loss_ratio,\n             y = policy_type,\n             fill = policy_type)) +\n  geom_density_ridges(alpha = 0.7,\n                      scale = 0.9,\n                      quantile_lines = TRUE,\n                      quantiles = 2) +\n  scale_fill_manual(values = c(\n    \"Comprehensive with Excess\"    = \"#4a7c6f\",\n    \"Comprehensive without Excess\" = \"#7aadab\",\n    \"Third-Party\"                  = \"#d4e8e1\",\n    \"Third-Party Combined\"         = \"#2d5a51\",\n    \"Third-Party with Glass\"       = \"#a8d5c2\")) +\n  labs(title = \"Distribution of Loss Ratio by Policy Type\",\n       subtitle = \"Vertical line shows median\",\n       x = \"Loss Ratio\",\n       y = \"Policy Type\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\nThe ridgeline plot provides a clearer view of how loss ratio distributions differ across policy types. **Comprehensive with Excess** and **Third-Party Combined** show the narrowest and most concentrated distributions, peaking sharply around 1–2, indicating consistent and predictable loss behaviour. Most notably, **Third-Party** policies exhibit a distinctive bimodal distribution with two peaks, one around 1–2 and another around 4–5, suggesting two distinct subgroups with very different loss behaviours.\n\n## Claim Frequency by Bonus Score\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_cf %>%\n  ggplot(aes(x = claim_frequency,\n             y = bonus_score,\n             fill = bonus_score)) +\n  geom_density_ridges(alpha = 0.7,\n                      scale = 0.9,\n                      quantile_lines = TRUE,\n                      quantiles = 2) +\n  scale_fill_manual(values = c(\n    \"Good\"    = \"#4a7c6f\",\n    \"Neutral\" = \"#7aadab\",\n    \"Bad\"     = \"#d4e8e1\")) +\n  labs(title = \"Distribution of Claim Frequency by Bonus Score\",\n       subtitle = \"Vertical line shows median\",\n       x = \"Claim Frequency\",\n       y = \"Bonus Score\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\nThe ridgeline plot clearly shows distinct distribution shapes across bonus score groups. **Good** bonus score policies show a sharp, concentrated peak around 1. **Bad** bonus score policies show the widest and most right-skewed distribution, with a long tail extending beyond 6, visually confirming the statistical findings from Section 6.4 that policyholders with a poor claims history exhibit the most unpredictable claim behaviour in the portfolio.\n:::\n\n# 7 Summary\n\nThis study applied univariate and bivariate visual analytics techniques to explore a real-world motor vehicle insurance portfolio from a Spanish non-life insurance company, with the aim of uncovering key factors influencing portfolio profitability and volatility.\n\n## Key Findings\n\n**Portfolio Overview**\n\nThe portfolio is dominated by middle-aged drivers holding Third-Party Combined policies, with the vast majority of policyholders recording no claims. This suggests a generally low-risk customer base, with a small but significant minority of high-risk policyholders driving most of the portfolio's losses.\n\n**Profitability (Loss Ratio)**\n\nPolicy type emerges as the strongest differentiator of portfolio profitability. Basic Third-Party policies are the least profitable despite being the least common, while Comprehensive with Excess policies generate the most consistent and stable loss ratios. This suggests that broader coverage does not necessarily translate to higher losses — comprehensive policyholders tend to be more careful drivers who pay higher premiums.\n\nFuel type and circulation area, while statistically significant, have negligible practical impact on profitability and are unlikely to be meaningful underwriting factors on their own.\n\n**Volatility (Claim Frequency)**\n\nBonus score is the most powerful predictor of claim frequency. Policyholders with a Bad bonus score make significantly more frequent claims, contributing disproportionately to portfolio volatility. This confirms that past claims history is a reliable indicator of future claim behaviour.\n\nComprehensive without Excess policies stand out as the most volatile policy type, likely because the absence of an excess removes the financial disincentive to file small claims.\n\n## Recommendations for Future Research\n\n-   **Confirmatory Data Analysis** — Future studies should incorporate regression modelling to validate the findings from this exploratory analysis and establish more definitive relationships between the identified risk factors and portfolio outcomes.\n\n-   **Exploring Additional Variables** — Variables such as driver occupation, annual mileage, claims history duration and vehicle usage type could provide a more complete picture of risk segmentation.\n\n-   **Longitudinal Analysis** — Conducting longitudinal studies to track changes in loss ratios and claim frequencies over a longer time period can reveal trends and seasonal patterns that a three-year snapshot may not capture.\n\n-   **Incorporating External Data** — As highlighted by the Swiss Re Institute (2019), enriching the portfolio data with external sources such as traffic density, weather patterns and regional accident statistics could further refine segmentation and improve underwriting strategy.\n\n# 8 References\n\nSwiss Re Institute. (2019). *Advanced analytics: Unlocking new frontiers in P&C insurance* (sigma No. 4/2019). Swiss Re Management Ltd. https://www.swissre.com/dam/jcr:3257ef4b-fe20-45e2-9700-7677702407af/sigma4_2019_en.pdf\n\nPesantez-Narvaez, J. (2023). *Motor vehicle insurance portfolio dataset*. Mendeley Data, V1. https://data.mendeley.com/datasets/sw4jmdb2sm/1",
    "supporting": [
      "Take_Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/ggiraphjs-0.9.4/girafe.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/ggiraphjs-0.9.4/girafe.js\"></script>\n<script src=\"../site_libs/girafe-binding-0.9.6/girafe.js\"></script>\n<link href=\"../site_libs/liberation-sans-0.5.0/css/liberation-sans.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/liberation-serif-0.5.0/css/liberation-serif.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/liberation-mono-0.5.0/css/liberation-mono.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}